### ISSUE TITLE
Implementar Base de datos

### ISSUE THREAD

**Issue by PaulQueza** [PaulQueza/contruccionSoftware#8]

**Comment by m0rf3us1** [comment]
Consulta base de datos:
consulta marca de producto

![Image](https://user-images.githubusercontent.com/80698564/192690699-cd0e6db9-a403-46bf-b6f4-cfd502eaa720.png)

**Comment by m0rf3us1** [comment]
Consulta base de datos:
        Filtrado por genero 


![Image](https://user-images.githubusercontent.com/80698564/192691008-36a152ca-ac6c-45e9-b849-98278ca249b5.png)

**Comment by m0rf3us1** [comment]
Consulta base de datos:
        Filtro de producto por talla disponible


![Image](https://user-images.githubusercontent.com/80698564/192691220-df87fc86-cce1-489d-b21a-d61dcccbc5bc.png)

**Comment by m0rf3us1** [comment]
Consulta base de datos:
       Filtro de talla, color y tipo en una consulta



![Image](https://user-images.githubusercontent.com/80698564/192692712-f8c8e1d8-a64f-401b-86a3-79b4784180ec.png)
